### ISSUE TITLE
Feliz.Bulma.Calendar error FS0192 : internal error : the anonymous record has not been generated

### ISSUE THREAD

**Issue by viktorvan** [Dzoukr/Feliz.Bulma#16]
Hi,
I cannot compile my project after trying to add and using Feliz.Bulma.Calendar. I have installed the dependencies manually using paket and yarn, and running `femto` it reports that everything is ok. 

But as soon as I add `Calendar.calendar ...` to my view my project won't compile and I get this error:

> error FS0192 : internal error : the anonymous record <>f__AnonymousType2118640243`6 has not been generated in the pre-phase of generating this module

It's not a very descriptive error message, it could very well be that I am doing something wrong on my side, I just can figure out what.

Is there a working sample using Feliz.Bulma.Calendar available?

**Comment by Zaid-Ajaj** [comment]
@viktorvan You might need to upgrade fable-compiler since it seems unable to compile an anonymous record. 

@Dzoukr I think using anonymous records in library gives fable-compiler weird issues if they are only used internally. I suggest using normal F# records to avoid these pesky situations. I will try to send a repro to the Fable compiler repository since I have seen this before in one of my libraries

**Comment by viktorvan** [comment]
Yes, I got it to work using fable-compiler: 2.4.22.

**Comment by Dzoukr** [comment]
Thanks @Zaid-Ajaj, I'll check usage of anonymous recs and make new version if necessary.

**Comment by Dzoukr** [comment]
Fixed in `1.0.3`. Thanks
